// SPDX-License-Identifier: GPL-2.0
#include "vmlinux.h" // Generated by bpftool
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>

char LICENSE[] SEC("license") = "GPL";

// Define a tracepoint program attached to the entry of the execve syscall
SEC("tp/syscalls/sys_enter_execve")
int handle_execve_enter(struct trace_event_raw_sys_enter* ctx) {
    // Get the process ID
    pid_t pid = bpf_get_current_pid_tgid() >> 32;

    // Print a message using a kernel helper
    // Note: bpf_printk is simple for debugging but has limitations (rate-limited, small buffer).
    // Real programs often use maps + perf/ring buffers for data transfer.
    bpf_printk("Hello from eBPF! Process %d is executing...\n", pid);
    return 0;
}
